version: 2
updates:
  # Go modules update configuration
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # GitHub Actions update configuration
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
